#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export DOTFILES_MODULE_BASE="${DIR}"

vars=()
playbooks=()

for var in "${!DOTFILES_MODULE_@}"; do
	eval val=${!var}
	config="$val/config.yaml"
	vault="$val/vault.yaml"
	playbook="$val/playbook.yaml"

	if [[ -f "$config" ]]; then
		vars+=("-e" "@${config}")
	fi
	if [[ -f "$vault" ]]; then
		vars+=("-e" "@${vault}")
	fi
	if [[ -f "$playbook" ]]; then
		playbooks+=("${playbook}")
	fi
done

ansible-playbook \
	-i ./inventory \
	--ask-vault-pass \
	"${playbooks[@]}" \
	"${vars[@]}" \
	"$@"
