# Common
export LANG=en_US.UTF-8
export TERM=xterm-256color

# History
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

# FIX: Prevent: complete:13: command not found: compdef
autoload -Uz compinit
compinit

# Custom bins
export PATH="$HOME/.bin:$PATH"

# ruby
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
# chruby ruby-3.1.2

# node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# golang
export GOPATH="/opt/go"
export PATH="$GOROOT/bin:$PATH"

# brew
eval "$(/opt/homebrew/bin/brew shellenv)" # Add brew bins

# macos
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export NATIVEFIER_APPS_DIR=~/Applications/

# Start tmux on zsh started
if [ -z "$TMUX" ]
then
    tmux attach || tmux
fi

source ~/.aliases
source ~/.customizations

eval "$(starship init zsh)"
