# Init Antibody plugin system
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt

# TODO: check
export LANG=en_US.UTF-8
export TERM=xterm-256color
# History
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

# Golang
export GOPATH=$HOME/go
export PATH="/usr/local/go/bin:$HOME/go/bin:$PATH"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv virtualenv-init -)"
eval "$(pyenv init -)"

# Init completion
autoload -U compinit
compinit

# My scripts
export PATH="$HOME/.scripts:$PATH"

source ~/.aliases
{% for extension in config.get('shell_extensions', []) %}
source {{ extension }}
{% endfor %}
